# Generated by Django 5.0.7 on 2025-04-11 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_examplemodeleeerrr_delete_examplemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_text", models.CharField(max_length=700)),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "about",
            },
        ),
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "characteristic_title_1",
                    models.CharField(default="Many musical genres...", max_length=40),
                ),
                ("characteristic_text_1", models.CharField(max_length=400)),
                ("photo_1", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "characteristic_title_2",
                    models.CharField(default="Deep lyrics", max_length=40),
                ),
                ("characteristic_text_2", models.CharField(max_length=400)),
                ("photo_2", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "characteristic_title_3",
                    models.CharField(
                        default="Unique style, unique feeling", max_length=40
                    ),
                ),
                ("characteristic_text_3", models.CharField(max_length=400)),
                ("photo_3", models.ImageField(default=None, upload_to="polls_media")),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Grand-Manil, Namur, Belgium", max_length=65
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(default="+44 7849 905419", max_length=25),
                ),
                (
                    "email",
                    models.EmailField(
                        default="cconteconte23@gmail.com", max_length=256
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_title_1",
                    models.CharField(default="New Music Alert!", max_length=30),
                ),
                ("news_text_1", models.CharField(max_length=100)),
                ("photo_1", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "news_title_2",
                    models.CharField(default="Don't Miss Out!", max_length=30),
                ),
                ("news_text_2", models.CharField(max_length=100)),
                ("photo_2", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "news_title_3",
                    models.CharField(default="Behind the Scenes", max_length=30),
                ),
                ("news_text_3", models.CharField(max_length=100)),
                ("photo_3", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "news_title_4",
                    models.CharField(default="Fan Art Friday", max_length=30),
                ),
                ("news_text_4", models.CharField(max_length=100)),
                ("photo_4", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "news_title_5",
                    models.CharField(default="Vanbarkas in the News", max_length=30),
                ),
                ("news_text_5", models.CharField(max_length=100)),
                ("photo_5", models.ImageField(default=None, upload_to="polls_media")),
                (
                    "news_title_6",
                    models.CharField(default="Happy Birthday", max_length=30),
                ),
                ("news_text_6", models.CharField(max_length=100)),
                ("photo_6", models.ImageField(default=None, upload_to="polls_media")),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_photo",
                    models.ImageField(default=None, upload_to="polls_media"),
                ),
                (
                    "opinions_fan_info_1",
                    models.CharField(default="Pete Rock, from Croatia", max_length=50),
                ),
                ("opinions_text_1", models.CharField(max_length=500)),
                (
                    "opinions_fan_info_2",
                    models.CharField(
                        default="Michael Snowden, from Ecuador", max_length=50
                    ),
                ),
                ("opinions_text_2", models.CharField(max_length=500)),
                (
                    "opinions_fan_info_3",
                    models.CharField(default="Tom Davis, from Nigeria", max_length=50),
                ),
                ("opinions_text_3", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Social_Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        default="https://www.facebook.com/djuphi.vanbarkas",
                        max_length=200,
                    ),
                ),
                ("instagram", models.CharField(default="", max_length=200)),
                ("linkedin", models.CharField(default="", max_length=200)),
                (
                    "youtube",
                    models.CharField(
                        default="https://www.youtube.com/@carlosconte7741",
                        max_length=200,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        default="https://wa.me/+447849905419", max_length=200
                    ),
                ),
                (
                    "youtube_video",
                    models.CharField(
                        default='<iframe width="1" height="1" src="https://www.youtube.com/embed/oU3KWPxQzOA" title="KAl Ki I DI Bô" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                        max_length=1000,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.CreateModel(
            name="What_I_do",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_1", models.CharField(max_length=20)),
                ("about_text_1", models.CharField(max_length=230)),
                ("topic_2", models.CharField(max_length=20)),
                ("about_text_2", models.CharField(max_length=230)),
                ("topic_3", models.CharField(max_length=20)),
                ("about_text_3", models.CharField(max_length=230)),
            ],
            options={
                "verbose_name_plural": "What I do",
            },
        ),
        migrations.DeleteModel(
            name="ExampleModeleeerrr",
        ),
    ]
